import React, { useState, useEffect } from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import axios from 'axios';
import Signup from './Signup';
import Login from './Login';
import Home from './Home';
import ProtectedRoute from './ProtectedRoute';
import Navbar from './Navbar';
import './App.css'; // We'll add some basic styles

function App() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [selectedFile, setSelectedFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [result, setResult] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (token) {
      setIsAuthenticated(true);
    }
  }, []);

  const handleLogin = () => {
    setIsAuthenticated(true);
  };

  const handleLogout = () => {
    localStorage.removeItem('token');
    setIsAuthenticated(false);
  };

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    if (file) {
      setSelectedFile(file);
      setResult(null); // Reset result on new file
      setError(null);  // Reset error
      // Create a preview URL
      setPreview(URL.createObjectURL(file));
    }
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (!selectedFile) {
      setError('Please select an image file first.');
      return;
    }

    setIsLoading(true);
    setError(null);
    setResult(null);

    // We use FormData to send the file
    const formData = new FormData();
    formData.append('image', selectedFile);

    const token = localStorage.getItem('token');
    try {
      const response = await axios.post(`${import.meta.env.VITE_API_URL}/api/analyze`, formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
          'Authorization': `Bearer ${token}`,
        },
      });
      setResult(response.data);
    } catch (err) {
      console.error(err);
      setError('Analysis failed. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const ImageDetector = () => (
    <div className="container">
        <h1>AI or Real? Image Detector</h1>
        <p>Upload an image to see if it was generated by AI.</p>

      <form onSubmit={handleSubmit}>
        <input type="file" accept="image/png, image/jpeg" onChange={handleFileChange} />
        <button type="submit" disabled={isLoading || !selectedFile}>
          {isLoading ? 'Analyzing...' : 'Analyze Image'}
        </button>
      </form>

      {error && <p className="error">{error}</p>}

      <div className="content-area">
        {preview && !result && (
          <div className="preview-box">
            <h3>Preview:</h3>
            <img src={preview} alt="Selected preview" />
          </div>
        )}

        {isLoading && <div className="loader"></div>}

        {result && (
          <div className="result-box">
            <img src={preview} alt="Analyzed" className="result-image" />
            <div className="result-details">
              <h2 className={result.is_ai ? 'ai' : 'real'}>
                {result.is_ai ? 'AI-Generated' : 'Likely Real'}
              </h2>
              <p>
                <strong>Confidence:</strong> 
                <span> {Math.round(result.confidence * 100)}%</span>
              </p>
              <p>
                <strong>Reason:</strong> {result.reason}
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );

  return (
    <Router>
      <Navbar isAuthenticated={isAuthenticated} onLogout={handleLogout} />
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/signup" element={<Signup />} />
        <Route path="/login" element={<Login onLogin={handleLogin} />} />
        <Route
          path="/detect"
          element={
            <ProtectedRoute isAuthenticated={isAuthenticated}>
              <ImageDetector />
            </ProtectedRoute>
          }
        />
        <Route path="*" element={<Navigate to="/" replace />} />
      </Routes>
    </Router>
  );
}

export default App;
