import React from 'react';
import { Link } from 'react-router-dom';
import './Home.css'; // We'll add styles for the home page

function Home() {
  return (
    <div className="home-container">
      <header className="hero-section">
        <h1 className="hero-title animate-fade-in">AI or Real? Image Detector</h1>
        <p className="hero-subtitle animate-slide-up">
          Discover the truth behind images in an era of advanced AI generation.
        </p>
        <Link to="/login" className="cta-button animate-bounce">
          Get Started
        </Link>
      </header>

      <section className="description-section">
        <div className="description-content">
          <h2 className="section-title animate-fade-in-delay">Why Image Detection Matters</h2>
          <p className="description-text animate-slide-up-delay">
            In today's digital world, artificial intelligence can create incredibly realistic images that are indistinguishable from real photographs. This technology has revolutionized creativity and design, but it also poses challenges in verifying authenticity. Misinformation, deepfakes, and manipulated content can spread rapidly, affecting journalism, social media, and even legal proceedings.
          </p>
          <p className="description-text animate-slide-up-delay">
            Our AI Image Detector uses cutting-edge machine learning algorithms to analyze images and determine whether they were likely generated by AI or captured in the real world. With high accuracy and fast processing, it helps users, content creators, and professionals make informed decisions about the media they encounter.
          </p>
        </div>
        <div className="animated-images">
          <img src="/vite.svg" alt="AI Generated Example" className="animated-image animate-float" />
          <img src="/vite.svg" alt="Real Image Example" className="animated-image animate-float-delay" />
        </div>
      </section>

      <section className="features-section">
        <h2 className="section-title animate-fade-in-delay">Key Features</h2>
        <div className="features-grid">
          <div className="feature-card animate-slide-up">
            <h3>High Accuracy</h3>
            <p>Advanced AI models trained on millions of images for reliable detection.</p>
          </div>
          <div className="feature-card animate-slide-up-delay">
            <h3>Fast Analysis</h3>
            <p>Get results in seconds, not minutes.</p>
          </div>
          <div className="feature-card animate-slide-up-delay-2">
            <h3>User-Friendly</h3>
            <p>Simple upload interface accessible to everyone.</p>
          </div>
          <div className="feature-card animate-slide-up-delay-3">
            <h3>Secure & Private</h3>
            <p>Your images are processed securely and not stored permanently.</p>
          </div>
        </div>
      </section>

      <footer className="footer">
        <p>&copy; 2024 AI Image Detector. Empowering truth in the digital age.</p>
      </footer>
    </div>
  );
}

export default Home;
