import React, { useState } from 'react';
import axios from 'axios';
import './Home.css'; // We'll add styles for the home page

function Home() {
  const [selectedFile, setSelectedFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [result, setResult] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    if (file) {
      setSelectedFile(file);
      setResult(null); // Reset result on new file
      setError(null);  // Reset error
      // Create a preview URL
      setPreview(URL.createObjectURL(file));
    }
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (!selectedFile) {
      setError('Please select an image file first.');
      return;
    }

    setIsLoading(true);
    setError(null);
    setResult(null);

    // We use FormData to send the file
    const formData = new FormData();
    formData.append('image', selectedFile);

    try {
      const response = await axios.post(`${import.meta.env.VITE_API_URL}/api/analyze`, formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      });
      setResult(response.data);
    } catch (err) {
      console.error(err);
      setError('Analysis failed. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="home-container">
      <header className="hero-section">
        <h1 className="hero-title animate-fade-in">AI or Real? Image Detector</h1>
        <p className="hero-subtitle animate-slide-up">
          Discover the truth behind images in an era of advanced AI generation.
        </p>
        <div className="hero-upload-section">
          <div className="upload-container">
            <input
              type="file"
              accept="image/png, image/jpeg"
              onChange={handleFileChange}
              id="hero-file-input"
              className="hero-file-input"
            />
            <label htmlFor="hero-file-input" className="hero-upload-button">
              <span className="upload-icon">📷</span>
              Choose Image to Analyze
            </label>
            <button
              type="button"
              onClick={handleSubmit}
              disabled={isLoading || !selectedFile}
              className="hero-analyze-button"
            >
              {isLoading ? 'Analyzing...' : 'Analyze Now'}
            </button>
            {preview && (
              <div className="image-preview">
                <img src={preview} alt="Image Preview" className="preview-image" />
              </div>
            )}
          </div>
          {error && <p className="hero-error">{error}</p>}
        </div>
      </header>

      {result && (
        <section className="results-section">
          <div className="results-container">
            <h2 className="results-title">Analysis Results</h2>
            <div className="result-box">
              <img src={preview} alt="Analyzed" className="result-image" />
              <div className="result-details">
                <h2 className={result.is_ai ? 'ai' : 'real'}>
                  {result.is_ai ? 'AI-Generated' : 'Likely Real'}
                </h2>
                <p>
                  <strong>Confidence:</strong>
                  <span> {Math.round(result.confidence * 100)}%</span>
                </p>
                <p>
                  <strong>Reason:</strong> {result.reason}
                </p>
              </div>
            </div>
          </div>
        </section>
      )}

      <section className="description-section">
        <div className="description-content">
          <h2 className="section-title animate-fade-in-delay">Why Image Detection Matters</h2>
          <p className="description-text animate-slide-up-delay">
            In today's digital world, artificial intelligence can create incredibly realistic images that are indistinguishable from real photographs. This technology has revolutionized creativity and design, but it also poses challenges in verifying authenticity. Misinformation, deepfakes, and manipulated content can spread rapidly, affecting journalism, social media, and even legal proceedings.
          </p>
          <p className="description-text animate-slide-up-delay">
            Our AI Image Detector uses cutting-edge machine learning algorithms to analyze images and determine whether they were likely generated by AI or captured in the real world. With high accuracy and fast processing, it helps users, content creators, and professionals make informed decisions about the media they encounter.
          </p>
        </div>

      </section>

      <section className="features-section">
        <h2 className="section-title animate-fade-in-delay">Key Features</h2>
        <div className="features-grid">
          <div className="feature-card animate-slide-up">
            <h3>High Accuracy</h3>
            <p>Advanced AI models trained on millions of images for reliable detection.</p>
          </div>
          <div className="feature-card animate-slide-up-delay">
            <h3>Fast Analysis</h3>
            <p>Get results in seconds, not minutes.</p>
          </div>
          <div className="feature-card animate-slide-up-delay-2">
            <h3>User-Friendly</h3>
            <p>Simple upload interface accessible to everyone.</p>
          </div>
          <div className="feature-card animate-slide-up-delay-3">
            <h3>Secure & Private</h3>
            <p>Your images are processed securely and not stored permanently.</p>
          </div>
        </div>
      </section>



      <footer className="footer">
        <p>&copy; 2024 AI Image Detector. Empowering truth in the digital age.</p>
      </footer>
    </div>
  );
}

export default Home;
